<a href="https://colab.research.google.com/github/WESTZERO115/EoI/blob/main/SeoYoung/TIL/AI_Programming/Examples/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

print(tf.__version__)
a = tf.random.uniform([2,3], 0, 1)
print(a)
print(type(a))

2.6.0
tf.Tensor(
[[0.8530177  0.02292967 0.04089797]
 [0.03220987 0.97411835 0.3959893 ]], shape=(2, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [3]:
import tensorflow as tf
import numpy as np

t = tf.random.uniform([2,3], 0, 1)
n = np.random.uniform(0,1,[2,3])
print("tensorflow로 생성한 텐서:\n", t, "\n")
print("numpy로 생성한 ndarray:\n", n, "\n")

res = t+n
print("덧셈 결과:|n", res)

tensorflow로 생성한 텐서:
 tf.Tensor(
[[0.3511374  0.8063284  0.9467541 ]
 [0.52388597 0.7481432  0.7255702 ]], shape=(2, 3), dtype=float32) 

numpy로 생성한 ndarray:
 [[0.64401801 0.46278376 0.16245164]
 [0.06118647 0.81776416 0.1404611 ]] 

덧셈 결과:|n tf.Tensor(
[[0.9951554  1.2691121  1.1092057 ]
 [0.58507246 1.5659074  0.8660313 ]], shape=(2, 3), dtype=float32)


In [ ]:
딥러닝에서는 데이터를 '텐서(tensor)'라는 자료구조로 표현한다.
즉, 다차원 배열.

numpy 라이브러리는 텐서를 ndarray 클래스라고 표현,
tensorflow 라이브러리는 텐서를 Tensor 클래스라고 표현.

이론 상 텐서플로는 무한 차원의 텐서를 다룰 수 있는데 보통 5차원 정도까지 다룬다.
텐서플로 라이브러리가 제공하는 데이터셋 예시로는, [MNIST, CIFAR-10, Boston Housing, Reuters]

텐서플로에서 Variable은 신경망의 가중치에 해당한다.

In [5]:
import tensorflow as ft

x = [[0.0,0.0], [0.0,0.1], [1.0,0.0], [1.0, 1.0]]
y = [[-1], [1], [1], [1]]

w = tf.Variable([[1.0], [1.0]])
b = tf.Variable(-0.5)

s = tf.add(tf.matmul(x,w),b)
o = tf.sign(s)

print(o)

tf.Tensor(
[[-1.]
 [-1.]
 [ 1.]
 [ 1.]], shape=(4, 1), dtype=float32)


In [ ]:
케라스는 한 단계 더 추상화함으로써 프로그래머의 수고를 덜어준다.
층을 하나 추가할 때도 model.add(Dense(노드의 개수, 활성함수,...)) 형식으로 간단하게 가능하다.

tensorflow 클래스의 하위에 편입되었음.


In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

x = [[0.0,0.0], [0.0,1.0], [1.0,0.0], [1.0,1.0]]
y = [[-1], [1], [1], [1]]

n_input = 2
n_output = 1

perceptron = Sequential()
perceptron.add(Dense(units=n_output, activation='tanh', input_shape=(n_input,), kernel_initializer='random_uniform', bias_initializer='zeros'))

perceptron.compile(loss='mse', optimizer=SGD
(learning_rate = 0.1), metrics = ['mse'])
perceptron.fit(x,y,epochs=500, verbose=2)

res = perceptron.predict(x)
print(res)

Epoch 1/500
1/1 - 1s - loss: 1.0583 - mse: 1.0583
Epoch 2/500
1/1 - 0s - loss: 0.7826 - mse: 0.7826
Epoch 3/500
1/1 - 0s - loss: 0.6596 - mse: 0.6596
Epoch 4/500
1/1 - 0s - loss: 0.6009 - mse: 0.6009
Epoch 5/500
1/1 - 0s - loss: 0.5663 - mse: 0.5663
Epoch 6/500
1/1 - 0s - loss: 0.5419 - mse: 0.5419
Epoch 7/500
1/1 - 0s - loss: 0.5226 - mse: 0.5226
Epoch 8/500
1/1 - 0s - loss: 0.5059 - mse: 0.5059
Epoch 9/500
1/1 - 0s - loss: 0.4908 - mse: 0.4908
Epoch 10/500
1/1 - 0s - loss: 0.4767 - mse: 0.4767
Epoch 11/500
1/1 - 0s - loss: 0.4633 - mse: 0.4633
Epoch 12/500
1/1 - 0s - loss: 0.4506 - mse: 0.4506
Epoch 13/500
1/1 - 0s - loss: 0.4383 - mse: 0.4383
Epoch 14/500
1/1 - 0s - loss: 0.4265 - mse: 0.4265
Epoch 15/500
1/1 - 0s - loss: 0.4151 - mse: 0.4151
Epoch 16/500
1/1 - 0s - loss: 0.4040 - mse: 0.4040
Epoch 17/500
1/1 - 0s - loss: 0.3934 - mse: 0.3934
Epoch 18/500
1/1 - 0s - loss: 0.3831 - mse: 0.3831
Epoch 19/500
1/1 - 0s - loss: 0.3732 - mse: 0.3732
Epoch 20/500
1/1 - 0s - loss: 0.3636 - m